#!/usr/bin/env php
<?php

use App\Console\Kernel;
use Imhotep\Framework\Application;
use Imhotep\Console\Output\ConsoleOutput;

define('IMHOTEP_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = new Application(
  dirname(__FILE__)
);

$app->alias('request', \Imhotep\Contracts\Http\Request::class);
$app->alias('response', \Imhotep\Contracts\Http\Response::class);

$app->singleton(\Imhotep\Contracts\Http\Request::class, \Imhotep\Http\Request::class);
$app->singleton(\Imhotep\Contracts\Http\Response::class, \Imhotep\Http\Response::class);

$app->bind(\Imhotep\Contracts\Debug\ExceptionHandler::class, \App\Exceptions\Handler::class);

$kernel = $app->make(Kernel::class);

$status = ($kernel->handle(
  $input = new \Imhotep\Console\Input\InputArgv(),
  new ConsoleOutput()
));

$kernel->terminate($input, $status);

exit($status);