#!/usr/bin/env php
<?php

use Imhotep\Console\Input\ArgvInput;

define('IMHOTEP_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require_once(__DIR__.'/app/app.php');

$status = $app->handleCommand(new ArgvInput());

exit($status);